# Generated by Django 4.1.13 on 2024-03-29 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryCharge',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('charge', models.IntegerField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
