# Generated by Django 4.1.13 on 2024-04-05 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecomApp', '0002_deliverycharge'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='walet',
            field=models.FloatField(default=1111),
            preserve_default=False,
        ),
    ]
