# Generated by Django 4.1.13 on 2024-04-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='walet_value',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
