# Generated by Django 4.1.13 on 2024-04-07 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_walet_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pick_up',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
